apiVersion: apps/v1
kind: Deployment
metadata:
  name: ask-renderer
  namespace: askorium
  labels:
    app: ask-renderer
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ask-renderer
  template:
    metadata:
      labels:
        app: ask-renderer
    spec:
      containers:
        - name: ask-renderer
          image: ghcr.io/umu-art/ask-renderer:main
          ports:
            - name: http
              containerPort: 8080

          envFrom:
            - secretRef:
                name: ask-renderer

          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3

          resources:
            requests:
              cpu: "200m"
              memory: "500M"
            limits:
              memory: "1G"

          securityContext:
            allowPrivilegeEscalation: false

      imagePullSecrets:
        - name: github-container-registry

      restartPolicy: Always
