name: "Deploy to stand"
description: "Apply new image to the stand via kubectl rollout restart"

inputs:
  kubesecret:
    description: "kubesecret"
    required: true
  module-name:
    description: "Модуль для синхронизации"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set the Kubernetes context
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ inputs.kubesecret }}

    - name: Deploy ${{ inputs.module-name }}
      if: inputs.deployment != 'false' && inputs.module-name != 'ask-encoder'
      shell: bash
      run: kubectl rollout restart deployment/${{ inputs.module-name }} -n askorium
