apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ask-encoder
  namespace: argocd
  labels:
    app.kubernetes.io/instance: askorium
spec:
  destination:
    namespace: askorium
    server: https://kubernetes.default.svc
  source:
    path: iac/kubernetes/ask-encoder
    repoURL: https://github.com/umu-art/askorium
    targetRevision: HEAD
    directory:
      recurse: true
  project: askorium
