openapi: 3.1.0

info:
  title: Search Api
  description: Минимальный api для поиска.
  version: 1.0.0

paths:
  /ask/query:
    post:
      tags:
        - search
      operationId: createSearchQuery
      summary: Создать поисковый запрос (асинхронно)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchCreateRequest"
      responses:
        202:
          description: Запрос создан
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchCreateResponse"

  /ask/query/{queryId}:
    get:
      tags:
        - search
      operationId: getSearchQueryResult
      summary: Получить статус или результат поискового запроса
      parameters:
        - name: queryId
          in: path
          required: true
          schema:
            type: string
            format: uuid
            description: UUID-идентификатор поискового запроса
      responses:
        200:
          description: Статус или результат
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchGetResponse"

components:
  schemas:
    SearchCreateRequest:
      type: object
      required:
        - query
        - sourceId
      properties:
        query:
          type: string
          minLength: 1
          maxLength: 2000
          description: Поисковый запрос
          example: "Как подключить OAuth2 в моём приложении?"
        sourceId:
          type: string
          format: uuid
          description: Идентификатор источника для поиска.
        mode:
          $ref: "#/components/schemas/SearchMode"

    SearchMode:
      type: string
      enum:
        - fast
        - deep

    SearchCreateResponse:
      type: object
      required:
        - queryId
      properties:
        queryId:
          type: string
          format: uuid
          description: UUID-идентификатор поискового запроса

    SearchStatus:
      type: string
      enum:
        - RUNNING
        - DONE
        - FAILED

    SearchGetResponse:
      type: object
      required:
        - queryId
        - status
      properties:
        queryId:
          type: string
          format: uuid
          description: UUID-идентификатор поискового запроса
        status:
          $ref: "#/components/schemas/SearchStatus"
        answer:
          type: string
          description: Сгенерированный ответ (если DONE)
        sources:
          type: array
          description: Ссылки и выдержки из источников (если DONE)
          items:
            $ref: "#/components/schemas/SourceSnippet"

    SourceSnippet:
      type: object
      required:
        - url
        - title
        - text
      properties:
        url:
          type: string
          example: "https://www.hse.ru/"
        title:
          type: string
          example: "Документация по OAuth2"
        date:
          type: string
          format: date-time
          description: Дата создания страницы/документа
          examples:
            - "2025-09-12T10:15:30Z"
        text:
          type: string
          description: Текст найденного фрагмента, релевантного запросу
          example: "Чтобы подключить OAuth2 в вашем приложении, нужно зарегистрировать его в нашей системе и получить client_id и client_secret..."
        scoreFinal:
          type: number
          format: float