apiVersion: apps/v1
kind: Deployment
metadata:
  name: ask-encoder
  namespace: askorium
  labels:
    app: ask-encoder
spec:
  replicas: 0
  selector:
    matchLabels:
      app: ask-encoder
  template:
    metadata:
      labels:
        app: ask-encoder
    spec:
      containers:
        - name: ask-encoder
          image: ghcr.io/umu-art/ask-encoder:main
          ports:
            - name: http
              containerPort: 8000

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 15
            failureThreshold: 3

          resources:
            requests:
              cpu: "200m"
              memory: "1G"
            limits:
              cpu: "2000m"
              memory: "2G"

          securityContext:
            allowPrivilegeEscalation: false

      imagePullSecrets:
        - name: github-container-registry

      restartPolicy: Always
