apiVersion: apps/v1
kind: Deployment
metadata:
  name: ask-core
  namespace: askorium
  labels:
    app: ask-core
spec:
  replicas: 0
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ask-core
  template:
    metadata:
      labels:
        app: ask-core
    spec:
      containers:
        - name: ask-core
          image: ghcr.io/umu-art/ask-core:main
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - secretRef:
                name: ask-core

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3

          resources:
            requests:
              cpu: "200m"
              memory: "600M"
            limits:
              memory: "1G"

          securityContext:
            allowPrivilegeEscalation: false

      imagePullSecrets:
        - name: github-container-registry

      restartPolicy: Always
