apiVersion: v1
kind: ConfigMap
metadata:
  name: ask-core-otel-config
  namespace: askorium
  labels:
    app: ask-core
data:
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://obs.kazenin.ru:21890"
  OTEL_METRICS_EXPORTER: "none"
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: "http://obs.kazenin.ru:21892"
  OTEL_INSTRUMENTATION_METHODS_INCLUDE: "ru.*.*[*]"
