apiVersion: v1
kind: ConfigMap
metadata:
  name: ask-core-otel-config
  namespace: askorium
  labels:
    app: ask-core
data:
  OTEL_JAVAAGENT_DEBUG: "true"
  OTEL_SERVICE_NAME: "ask-core"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://obs.kazenin.ru:21890"
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: "http://obs.kazenin.ru:21891"
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: "http://obs.kazenin.ru:21892"
  OTEL_INSTRUMENTATION_METHODS_INCLUDE: "ru.*[*]"
  OTEL_INSTRUMENTATION_METHODS_ENABLED: "true"
  OTEL_INSTRUMENTATION_OPENSEARCH_JAVA_ENABLED: "true"
  OTEL_INSTRUMENTATION_RABBITMQ_ENABLED: "true"
  OTEL_INSTRUMENTATION_REDISSON_ENABLED: "true"
  OTEL_INSTRUMENTATION_SPRING_DATA_ENABLED: "true"
  OTEL_INSTRUMENTATION_SPRING_WEB_ENABLED: "true"


  