apiVersion: v1
kind: Service
metadata:
  name: ask-core
  namespace: askorium
  labels:
    app: ask-core
spec:
  selector:
    app: ask-core
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
