generatorName: go
outputDir: build/renderer-model

additionalProperties:
  packageName: renderer_model
  packageVersion: 1.0.0
  isGoSubmodule: true
  enumClassPrefix: true
  structPrefix: true
  withXml: false
  generateGoMod: false
  generateReadme: false
  generateInterfaces: true

globalProperties:
  models: ''
  apis: ''
  supportingFiles:
    - utils.go
    - client.go
    - configuration.go
    - response.go
  modelTests: false
  apiTests: false
  modelDocs: false
  apiDocs: false