sources:
  - renderer-api.yaml
target: go-renderer-api
generatorName: go

additionalProperties:
  packageName: renderer_model
  isGoSubmodule: false
  enumClassPrefix: true
  structPrefix: true
  withGoMod: true

globalProperties:
  models: ''
  apis: false
  supportingFiles:
    - utils.go
    - go.mod
    - go.sum
  modelTests: false
  apiTests: false
  modelDocs: false
  apiDocs: false