sources:
  - encoder-api.yaml
  - source-api.yaml
target: java-ask-api
generatorName: java

additionalProperties:
  artifactId: ask-api
  groupId: ru.askorium

  basePackage: ru.askorium.api
  invokerPackage: ru.askorium.api.client
  modelPackage: ru.askorium.api.model
  apiPackage: ru.askorium.api.client

  generateBuilders: true
  useJakartaEe: true
  library: resttemplate
  dateLibrary: java8

globalProperties:
  supportingFiles:
    - ApiClient.java
    - BaseApi.java
    - JavaTimeFormatter.java
    - RFC3339DateFormat.java
    - RFC3339InstantDeserializer.java
    - RFC3339JavaTimeModule.java
    - Authentication.java

  apis: ''

  modelTests: false
  apiTests: false
  modelDocs: false
  apiDocs: false
