apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ask-scrapper
  namespace: askorium
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: ask-scrapper
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: ask-scrapper
