// Package scrapper_model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package scrapper_model

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ContentBlockType.
const (
	ContentBlockTypeHeading   ContentBlockType = "heading"
	ContentBlockTypeListItem  ContentBlockType = "listItem"
	ContentBlockTypeParagraph ContentBlockType = "paragraph"
)

// Defines values for DocumentDescriptionSourceType.
const (
	DocumentDescriptionSourceTypeHeading   DocumentDescriptionSourceType = "heading"
	DocumentDescriptionSourceTypeListItem  DocumentDescriptionSourceType = "listItem"
	DocumentDescriptionSourceTypeParagraph DocumentDescriptionSourceType = "paragraph"
)

// Defines values for ErrorCode.
const (
	ACCESSDENIED ErrorCode = "ACCESS_DENIED"
	INVALIDURL   ErrorCode = "INVALID_URL"
	NETWORKERROR ErrorCode = "NETWORK_ERROR"
	PAGENOTFOUND ErrorCode = "PAGE_NOT_FOUND"
	PARSEERROR   ErrorCode = "PARSE_ERROR"
	RATELIMITED  ErrorCode = "RATE_LIMITED"
	TIMEOUT      ErrorCode = "TIMEOUT"
)

// Defines values for LinkType.
const (
	External LinkType = "external"
	Internal LinkType = "internal"
)

// ContentBlock defines model for ContentBlock.
type ContentBlock struct {
	// HeadingLevel Уровень заголовка (для type=heading).
	HeadingLevel *int    `json:"headingLevel,omitempty"`
	HtmlId       *string `json:"htmlId,omitempty"`

	// Text Очищённый текст блока.
	Text string `json:"text"`

	// Type Тип блока контента.
	Type ContentBlockType `json:"type"`
}

// ContentBlockType Тип блока контента.
type ContentBlockType string

// Document defines model for Document.
type Document struct {
	// Description Короткое текстовое описание (alt, caption или сгенерированное моделью).
	Description *string `json:"description,omitempty"`

	// DescriptionSource Источник описания документа.
	DescriptionSource *DocumentDescriptionSourceType `json:"descriptionSource,omitempty"`

	// ExtractedText Текст, извлечённый из файла (OCR / PDF text), если был извлечён.
	ExtractedText *string `json:"extractedText,omitempty"`

	// MimeType MIME-тип (image/jpeg, application/pdf и т.п.).
	MimeType string `json:"mimeType"`

	// SizeBytes Размер в байтах (если доступен).
	SizeBytes *int `json:"sizeBytes,omitempty"`

	// Url Ссылка на документ/изображение.
	Url string `json:"url"`
}

// DocumentDescriptionSourceType Источник описания документа.
type DocumentDescriptionSourceType string

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// Link Ссылка со страницы
type Link struct {
	// AnchorText Текст анкера (если есть).
	AnchorText *string `json:"anchorText,omitempty"`

	// ContextBlockId ID блока, внутри которого находится ссылка.
	ContextBlockId *string `json:"contextBlockId,omitempty"`

	// Href Целевой URL ссылки.
	Href string `json:"href"`

	// Position Начальная позиция ссылки внутри блока.
	Position int `json:"position"`

	// Snippet Небольшой контекст вокруг ссылки (короткий сниппет).
	Snippet *string `json:"snippet,omitempty"`

	// Type Тип ссылки (внутри домена или внешняя).
	Type LinkType `json:"type"`
}

// LinkType Тип ссылки (внутри домена или внешняя).
type LinkType string

// ScrapeError defines model for ScrapeError.
type ScrapeError struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ScrapeOptions defines model for ScrapeOptions.
type ScrapeOptions struct {
	ExtractDocuments *bool `json:"extract_documents,omitempty"`
	ExtractLinks     *bool `json:"extract_links,omitempty"`

	// MaxRetries Максимальное количество повторных попыток
	MaxRetries *int `json:"max_retries,omitempty"`

	// TimeoutMs Таймаут загрузки страницы (миллисекунды)
	TimeoutMs *int `json:"timeout_ms,omitempty"`
}

// ScrapeRequest defines model for ScrapeRequest.
type ScrapeRequest struct {
	// Metadata Сквозные данные, возвращаются без изменений
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Options  *ScrapeOptions          `json:"options,omitempty"`

	// TaskId Уникальный идентификатор задачи
	TaskId openapi_types.UUID `json:"task_id"`

	// Url URL для парсинга
	Url string `json:"url"`
}

// ScrapeResponse defines model for ScrapeResponse.
type ScrapeResponse struct {
	Error    *ScrapeError            `json:"error,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Page     *ScrappedPage           `json:"page,omitempty"`

	// Success Итоговый результат выполнения
	Success bool               `json:"success"`
	TaskId  openapi_types.UUID `json:"task_id"`
}

// ScrappedPage defines model for ScrappedPage.
type ScrappedPage struct {
	// Blocks Логические блоки текста (заголовки, абзацы).
	Blocks []ContentBlock `json:"blocks"`

	// Description Описание страницы
	Description *string `json:"description,omitempty"`

	// Documents Вложения (изображения, PDF и т.п.) с возможным описанием/текстом.
	Documents *[]Document `json:"documents,omitempty"`

	// IconUrl Ссылка на иконку страницы
	IconUrl *string `json:"iconUrl,omitempty"`

	// Language Язык страницы (например "ru", "en"), если определён.
	Language *string `json:"language,omitempty"`

	// LastModified Дата последнего изменения, если доступна.
	LastModified *time.Time `json:"lastModified,omitempty"`

	// Links Точные ссылки.
	Links *[]Link `json:"links,omitempty"`

	// PreviewUrl Ссылка на превью страницы
	PreviewUrl *string `json:"previewUrl,omitempty"`

	// Title Заголовок страницы
	Title string `json:"title"`

	// Url URL страницы.
	Url string `json:"url"`
}
