name: Assembling this whole mess

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    name: Build (${{ matrix.module }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: ask-core
            script: java

          - module: ask-encoder
            script: python

          - module: ask-parser
            script: go

          - module: ask-ui
            script: node

          - module: ask-renderer
            script: python

    uses: ./.github/workflows/_build-module.yml
    with:
      module: ${{ matrix.module }}
      script: ${{ matrix.script }}
      test-only: ${{ github.ref != 'refs/heads/main' || github.event_name != 'push' }}
    secrets: inherit

  sync-iac:
    needs:
      - build
    name: Sync IaC (ArgoCD)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync
        uses: ./.github/workflows/actions/argo_sync
        with:
          argocd-server: ${{ secrets.ARGOCD_SERVER }}
          argocd-token: ${{ secrets.ARGOCD_TOKEN }}
